Update profile

diff --git a/CustomFiles/Depends/profile b/CustomFiles/Depends/profile
--- a/CustomFiles/Depends/profile
+++ b/CustomFiles/Depends/profile
@@ -1,11 +1,47 @@
-[ -e /tmp/.failsafe ] && export FAILSAFE=1
-clear
-[ -f /etc/banner ] && cat /etc/banner
-[ -n "$FAILSAFE" ] && cat /etc/banner.failsafe
+Sysinfo() {
+	[ -f /etc/openwrt_info ] && source /etc/openwrt_info > /dev/null 2>&1
+	export Target=${DEFAULT_Device}
+	[ -n "${CURRENT_Version}" ] && export Version="${CURRENT_Version}" || Version=未知
+	[ -z "${Target}" ] && export Target=$(jsonfilter -e '@.model.id' < /etc/board.json | tr ',' '_')
+	export IP_Address=$(ifconfig -a | grep inet | grep -v 127.0.0.1 | grep -v inet6 | awk '{print $2}' | tr -d "addr:" | awk 'NR==1')
+	export CoreMark=$([ -f /etc/bench.log ] && egrep -o "[0-9]+" /etc/bench.log | awk 'NR==1')
+	export Startup=$(awk '{a=$1/86400;b=($1%86400)/3600;c=($1%3600)/60} {printf("%d 天 %d 小时 %d 分钟\n",a,b,c)}' /proc/uptime)
+	export Overlay_Available="$(df -h | grep ":/overlay" | awk '{print $4}' | awk 'NR==1')"
+	export TEMP=$(sensors 2>/dev/null | grep 'Core 0' | awk '{print $3}')
+	echo -e "\n           设备名称:		${Yellow}$(uname -n) / ${Target}${White}"
+	[ -n "${TEMP}" ] && echo "           核心温度:		${TEMP}"
+	echo "           内核版本:		$(uname -rs)"
+	echo -e "           固件版本:		${Skyb}${Version}${White}"
+	echo "           IP 地址 : 		${IP_Address}"
+	echo "           可用空间:		${Overlay_Available}"
+	[ -n "${CoreMark}" ] && echo "           性能得分:		${CoreMark}"
+	echo "           运行时间: 		${Startup}"
+	echo ""
+}
 
+White="\e[0m"
+Yellow="\e[33m"
+Red="\e[31m"
+Blue="\e[34m"
+Skyb="\e[36m"
+
+clear
+[ -e /tmp/.failsafe ] && export FAILSAFE=1
+[ -f /etc/banner ] && {
+	echo -e "$Skyb"
+	cat /etc/banner
+	echo -e "$White"
+}
+[ -n "$FAILSAFE" ] && {
+	echo -e "$Red"
+	cat /etc/banner.failsafe
+	echo -e "$White"
+}
 fgrep -sq '/ overlay ro,' /proc/mounts && {
-	echo '您的 JFFS2 分区似乎已满并且 overlayfs 挂载为只读.'
-	echo '请尝试从 /overlay/upper/... 删除文件并重启!'
+	echo -e "$Red"
+	echo "警告: 您的固件空间已满,接下来保存的数据将会面临丢失的风险."
+	echo "请尝试从 /overlay 删除一些文件并重启设备!"
+	echo -e "$White"
 }
 
 export PATH="/usr/sbin:/usr/bin:/sbin:/bin"
@@ -28,18 +64,20 @@ esac
 	unset FILE
 }
 
-Target=$([ -f /etc/openwrt_info ] && cat /etc/openwrt_info | awk 'NR==3')
-Version=$([ -f /etc/openwrt_info ] && cat /etc/openwrt_info | awk 'NR==1')
-[ -z "${Target}" ] && Target=$(jsonfilter -e '@.model.id' < /etc/board.json | tr ',' '_')
-IP_Address=$(ifconfig -a | grep inet | grep -v 127.0.0.1 | grep -v inet6 | awk '{print $2}' | tr -d "addr:" | awk 'NR==1')
-CoreMark=$([ -f /etc/bench.log ] && egrep -o "[0-9]+" /etc/bench.log | awk 'NR==1')
-[ -z "${CoreMark}" ] && CoreMark=0
-Srartup=$(awk '{a=$1/86400;b=($1%86400)/3600;c=($1%3600)/60} {printf("%d 天 %d 小时 %d 分钟\n",a,b,c)}' /proc/uptime)
-Overlay_Available="$(df -h | grep ":/overlay" | awk '{print $4}' | awk 'NR==1')"
+service() {
+	[ -f "/etc/init.d/$1" ] || {
+		echo -e "${Red}service "'"'"$1"'"'" not found, the following services are available:${White}\n"
+		ls "/etc/init.d"
+		return 1
+	}
+	/etc/init.d/$@
+}
 
-echo -e "\n\n           设备名称:		${Target}"
-echo "           固件版本:		${Version}"
-echo "           IP 地址: 		${IP_Address}"
-echo "           运行时间: 		${Srartup}"
-echo "           CoreMark 得分: 	${CoreMark}"
-echo -e "           可用空间:		${Overlay_Available}\n"
+Sysinfo
+alias reload='clear && /etc/profile'
+alias autoupdate='bash /bin/AutoUpdate.sh'
+alias tools='bash /bin/AutoBuild_Tools.sh'
+alias run_coremark='bash /etc/coremark.sh'
+alias shutdown='sync && poweroff'
+alias ll='ls -alF --color=auto'
+alias cls='clear'
